### ISSUE TITLE
Wrong request from dockerized app?

### ISSUE THREAD

**Issue by nikolay-turpitko** [ory-am/hydra-idp-react#6]
I'm trying to start this sample in the docker container, as described in readme.

But in the hydra container log I see:

time="2016-08-23T17:50:20Z" level=info msg="started handling request" method=POST remote="172.17.0.3:35390" request="/oauth/token" 
time="2016-08-23T17:50:20Z" level=info msg="completed handling request" measure#web.latency=105342 method=POST remote="172.17.0.3:35390" request="/oauth/token" status=404 text_status="Not Found" took=105.342µs

I believe, that it should be `/oauth2/token` not `/oauth/token`.

From line 22 in `/src/common/service/hydra.js` I conclude, that correct path is set only when there is a `.hydra.yml` file somewhere in the home dir, which is absent in case of docker. So, some default setting is probably used.

https://github.com/ory-am/hydra-idp-react/blob/b290b1415538e64be999756cb4f8745c3bd220b7/src/common/service/hydra.js#L22

**Comment by arekkas** [comment]
Hm it should always use that value. How did you initiate the flow? Using `hydra token user`? Did you run it locally or from the docker container?

**Comment by nikolay-turpitko** [comment]
I run 2 docker containers - one with demo app and one with hydra itself. I
attempted to login with predefined user in the demo app. I think, that demo
app sends wrong request, because it has no config file within docker
container, so mentioned lines won't execute in that case and some default
URL suffix is used.

1:39, ср, 24.08.2016 Aeneas <notifications@github.com>:

**Comment by arekkas** [comment]
Last time I checked the demo app worked. Are you using [this tutorial](https://ory-am.gitbooks.io/hydra/content/demo.html)?

**Comment by arekkas** [comment]
I can't reproduce this on my system

**Comment by nikolay-turpitko** [comment]
Not exactly. I started hydra in the docker, as described in installation,
then got client_id and client secret and set them via CLI flag when
starting docker container with app. So, both hydra and app are run in
separate docker containers. Containers are linked via CLI and app provided
with URL via env var using CLI.

1:49, ср, 24.08.2016 Aeneas <notifications@github.com>:

**Comment by nikolay-turpitko** [comment]
sudo docker run -d -p 4444:4444 \
    --name my-hydra \
    oryam/hydra

# env var values below are from logs of docker container  above

sudo docker run -d -p 3000:3000 \
    -e "CLIENT_ID=xxxxx" \
    -e "CLIENT_SECRET=xxxx" \
    -e "HYDRA_URL=https://my-hydra:4444" \
    -e "NODE_TLS_REJECT_UNAUTHORIZED=0" \
    --link my-hydra \
    --name my-hydra-consent-ui \
    oryam/hydra-idp-react

**Comment by arekkas** [comment]
Ah I see what you mean now, this line is preventing the correct set up: https://github.com/ory-am/hydra-idp-react/blob/b290b1415538e64be999756cb4f8745c3bd220b7/src/common/service/hydra.js#L14-L16

Instead, there should be something like:

```js
    return {
        clientID: config.client_id,
        clientSecret: config.client_secret,
        endpoint: config.cluster_url,
        tokenPath: '/oauth2/token',
        authorizationPath: '/oauth2/auth',
        scope: 'hydra.keys.get'
    }
```

Additionally, it looks like env vars `CLIENT_ID` or `CLIENT_SECRET` are not used there either.

I welcome PRs regarding this :)

**Comment by arekkas** [comment]
nevermind, i think it's even easier, I'll supply a fix.

**Comment by arekkas** [comment]
i've hotfixed this now, could you rebuild the image and try again?

**Comment by nikolay-turpitko** [comment]
Yep, this one seems to be fixed.

But now I got another error: "Could not verify consent challenge: JsonWebTokenError: jwt must be provided".

Here are lines from app's log:
```
Skipping TLS Verification because NODE_TLS_REJECT_UNAUTHORIZED is set to 0
{ error: 'Could not verify consent challenge: JsonWebTokenError: jwt must be provided' }

```

And these lines are from hydra container:
```
time="2016-08-24T03:15:22Z" level=info msg="started handling request" method=GET remote="172.17.0.3:45306" request="/keys/consent.challenge/public" 
time="2016-08-24T03:15:22Z" level=info msg="Access granted" audience=0a5c5291-xxxx subject=0a5c5291-xxxx
time="2016-08-24T03:15:22Z" level=info msg="completed handling request" measure#web.latency=605822 method=GET remote="172.17.0.3:45306" request="/keys/consent.challenge/public" status=200 text_status=OK took=605.822µs 

```

Can you suggest what I missed in setup?

**Comment by arekkas** [comment]
Looks like you didn't provide the content challenge. I recommend trying the tutorial first

**Comment by nikolay-turpitko** [comment]
To clarify, this app provides only consent page and does not handle final redirection with &code or &error, right? That part, that should exchange code for access token or display an error? I mean it's OK, but I want to confirm that I understand it right. So, my own client app should be a mix of this consent app and the code of the `hydra token user` command, right?

I was able to setup Hydra and this hydra-idp-react in 2 docker containers and went through steps till final redirect to /callback?code=xxx&scope=xxx&state=xxx. There is no part in my setup, which can handle this request, I suppose it is intended, and this should be implemented by the client app. I intentionally did not use `hydra token user` command, because I want to understand better what's going on and what parts I should implement in my app.

Also, I tried to create another client for test, and had to create 2 policies to read public and private keys, as you can see below. I do not fully understand policies. So, my question is how can I restrict usage of keys only by trusted apps? For example, if I want to make my API available to the external (not mine) apps as well as to my own privileged app, is it possible to allow request for keys available only to my privileged app, but disallow to others? Or should I make it other way, for example, by hiding url paths using proxy?

Here are steps, that I followed to setup:

```
# 1. start hydra

sudo docker run -d \
    -p 4444:4444 \
    --name my-hydra \
    -e "CONSENT_URL=http://localhost:3000" \
    oryam/hydra

# 2. get client_id and client_secret of default client from logs (to connect to Hydra with CLI)

sudo docker logs my-hydra

# 3. create client for test

sudo docker exec -i -t my-hydra /bin/bash

hydra connect --skip-tls-verify

hydra clients create -n "test" \
  -c [http://localhost:3000/callback] \
  -g [authorize_code,authorization_code,client_credentials] \
  -r [code,token] \
  -a [core,hydra.keys.get] \
  --skip-tls-verify

hydra policies create --allow -r "rn:hydra:keys:<[^:]+>:public" -s "<.*>" -a "get" --skip-tls-verify

hydra policies create --allow -r "rn:hydra:keys:<[^:]+>:private" -s "<.*>" -a "get" --skip-tls-verify

exit

# 4. put returned client_id and client_secret into ./hydra.yml

# 5. run ui-app

sudo docker run -d -p 3000:3000 \
    -v $(readlink -f hydra.yml):/root/.hydra.yml \
    -e "NODE_TLS_REJECT_UNAUTHORIZED=0" \
    --link my-hydra \
    --name my-hydra-consent-ui \
    oryam/hydra-idp-react


# 6. start from page like this (in firefox-dev, because of self-issued ssl keys, use client_id from #3):
#
# https://localhost:4444/oauth2/auth?client_id=xxx&response_type=code&scope=core+hydra.keys.get&state=vboeidlizlxrywkwlsgeggff&nonce=tedgziijemvninkuotcuuiof

```

**Comment by nikolay-turpitko** [comment]
BTW, I added both `authorize_code` and `authorization_code` to the `--grant-types` because former is mentioned in the README in this app, and later is used as example in the help to the command, I do not know which is right.

**Comment by nikolay-turpitko** [comment]
BTW, &nonce from the /oauth2/auth url seems not to be used anywhere in the hydra code. What is it for?

**Comment by arekkas** [comment]
The nonce is used for id tokens / openid connect.

Gesendet mit meinem HTC

----- Reply message -----
Von: "Nikolay Turpitko" <notifications@github.com>
An: "ory-am/hydra-idp-react" <hydra-idp-react@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Comment" <comment@noreply.github.com>
Betreff: [ory-am/hydra-idp-react] Wrong request from dockerized app? (#6)
Datum: Do., Aug. 25, 2016 15:08

BTW, &nonce from the /oauth2/auth url seems not to be used anywhere in the hydra code. What is it for?

**Comment by arekkas** [comment]
Yes the callback url is something the third party app implements.

In the future it will be possible to assign groups to policies and users/oauth2 clients to groups. Your policy use case should be totally fine, no need for proxies.

Gesendet mit meinem HTC

----- Reply message -----
Von: "Nikolay Turpitko" <notifications@github.com>
An: "ory-am/hydra-idp-react" <hydra-idp-react@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Comment" <comment@noreply.github.com>
Betreff: [ory-am/hydra-idp-react] Wrong request from dockerized app? (#6)
Datum: Do., Aug. 25, 2016 14:54

To clarify, this app provides only consent page and does not handle final redirection with &code or &error, right? That part, that should exchange code for access token or display an error? I mean it's OK, but I want to confirm that I understand it right. So, my own client app should be a mix of this consent app and the code of the `hydra token user` command, right?

I was able to setup Hydra and this hydra-idp-react in 2 docker containers and went through steps till final redirect to /callback?code=xxx&scope=xxx&state=xxx. There is no part in my setup, which can handle this request, I suppose it is intended, and this should be implemented by the client app. I intentionally did not use `hydra token user` command, because I want to understand better what's going on and what parts I should implement in my app.

Also, I tried to create another client for test, and had to create 2 policies to read public and private keys, as you can see below. I do not fully understand policies. So, my question is how can I restrict usage of keys only by trusted apps? For example, if I want to make my API available to the external (not mine) apps as well as to my own privileged app, is it possible to allow request for keys available only to my privileged app, but disallow to others? Or should I make it other way, for example, by hiding url paths using proxy?

Here are steps, that I followed to setup:

```
# 1. start hydra

sudo docker run -d \
-p 4444:4444 \
--name my-hydra \
-e "CONSENT_URL=http://localhost:3000" \
oryam/hydra

# 2. get client_id and client_secret of default client from logs (to connect to Hydra with CLI)

sudo docker logs my-hydra

# 3. create client for test

sudo docker exec -i -t my-hydra /bin/bash

hydra connect --skip-tls-verify

hydra clients create -n "test" \
-c [http://localhost:3000/callback] \
-g [authorize_code,authorization_code,client_credentials] \
-r [code,token] \
-a [core,hydra.keys.get] \
--skip-tls-verify

hydra policies create --allow -r "rn:hydra:keys:<[^:]+>:public" -s "<.*>" -a "get" --skip-tls-verify

hydra policies create --allow -r "rn:hydra:keys:<[^:]+>:private" -s "<.*>" -a "get" --skip-tls-verify

exit

# 4. put returned client_id and client_secret into ./hydra.yml

# 5. run ui-app

sudo docker run -d -p 3000:3000 \
-v $(readlink -f hydra.yml):/root/.hydra.yml \
-e "NODE_TLS_REJECT_UNAUTHORIZED=0" \
--link my-hydra \
--name my-hydra-consent-ui \
oryam/hydra-idp-react


# 6. start from page like this (in firefox-dev, because of self-issued ssl keys, use client_id from #3):
#
# https://localhost:4444/oauth2/auth?client_id=xxx&response_type=code&scope=core+hydra.keys.get&state=vboeidlizlxrywkwlsgeggff&nonce=tedgziijemvninkuotcuuiof

```

**Comment by nikolay-turpitko** [comment]
Thank you very mach!
